datasources:
  default:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver
jpa:
  default:
    entity-scan:
      packages:
        - 'ru.drudenko.model'
        - 'ru.drudenko.model.repository'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
micronaut:
  application:
    name: helloworld
  server:
    port: 8888